// Pipeline artifact types (JSON files under `data/`)

export interface SegmentYearIndexEntry {
  juan_index: number;
  segment_index: number;
  segment_start_time_raw: string | null;
  year: number | null;
  parse_method: string | null;
  confidence: number;
}

export interface SegmentYearIndex {
  version: string;
  cutoff_year: number;
  generated_at: string;
  segments: Record<string, SegmentYearIndexEntry>;
}

export interface SegmentYearOverrideEntry {
  year: number | null;
  reason?: string;
}

export interface SegmentYearOverrides {
  version: string;
  notes?: string;
  overrides: Record<string, SegmentYearOverrideEntry | number | null>;
}

export interface UnitProgressIndexUnit {
  unit_index: number;
  unit_title: string;
  season_index: number;
  season_name: string;
  progress_start: number;
  progress_end: number;
}

export interface UnitProgressIndexSegment {
  unit_index: number;
  segment_index: number;
  progress_index: number;
  progress_label: string;
}

export interface UnitProgressIndex {
  version: string;
  generated_at: string;
  book_id: string;
  unit_label: string;
  progress_label: string;
  total_units: number;
  total_progress_points: number;
  units: Record<string, UnitProgressIndexUnit>;
  segments: Record<string, UnitProgressIndexSegment>;
}

export interface ChapterIndexSegment {
  segment_index: number;
  progress_index: number;
  progress_label: string;
  anchor: string;
}

export interface ChapterIndexUnit {
  unit_index: number;
  juan_index: number;
  season_index: number;
  season_name: string;
  title: string;
  volume_index: number;
  volume_title: string;
  chapter_title: string;
  relative_path: string;
  progress_start: number;
  progress_end: number;
  source_document: string;
  segments: ChapterIndexSegment[];
}

export interface ChapterIndex {
  book_id: string;
  generated_at: string;
  unit_count: number;
  units: ChapterIndexUnit[];
}

export interface BookQuickFilter {
  label: string;
  unit_range: [number, number];
  progress_range: [number, number];
}

export interface BookConfig {
  book_id: string;
  title: string;
  subtitle?: string;
  book_overview_summary?: string;
  unit_label: string;
  progress_label: string;
  has_geo_coordinates: boolean;
  default_tab?:
  | 'timeline'
  | 'narrativeUnits'
  | 'network'
  | 'power'
  | 'locations'
  | 'map'
  | 'writerArcs'
  | 'conflicts'
  | 'foreshadowing';
  quick_filters: BookQuickFilter[];
}

export interface LocationGeocodingEntry {
  location_id: string;
  canonical_name: string;
  modern_name: string;
  query: string;
  coordinates: [number, number] | null;
  candidate_coordinates?: [number, number] | null;
  candidate_count?: number | null;
  confidence: number;
  source: string;
  evidence: string;
  info?: string;
  infocode?: string;
  needs_review: boolean;
  attempts?: number;
  updated_at: string;
}

export interface LocationGeocodingOverridesEntry {
  coordinates: [number, number];
  notes?: string;
}

export interface LocationGeocodingCache {
  version: string;
  provider: string;
  generated_at: string;
  locations: Record<string, LocationGeocodingEntry>;
  overrides: Record<string, LocationGeocodingOverridesEntry>;
}

// Chapter synopses (generated by build_chapter_synopses.py)

export interface KeyDevelopmentEvent {
  event_id: string;
  name: string;
  display_text: string;
  display_source?: 'evidence' | 'description' | 'name';
  evidence_excerpt?: string;
  participants: string[];
  location: string;
}

export interface ChapterSynopsis {
  unit_index: number;
  unit_title: string;
  season_name: string;
  event_count: number;
  active_characters: string[];
  locations: string[];
  key_developments: string[];
  key_development_events?: KeyDevelopmentEvent[];
  synopsis: string;
  narrative_function: string;
}

export interface ChapterSynopsesPayload {
  version: string;
  generated_at: string;
  book_id: string;
  chapter_count: number;
  chapters: ChapterSynopsis[];
}

/* ── Key Events Index ── */

export interface KeyEvent {
  event_id: string;
  name: string;
  event_type: string;
  importance: 'critical' | 'major' | 'notable';
  score: number;
  location: string;
  participants: string[];
  description: string;
  significance: string;
  involved_characters: string[];
  // Card-granularity fields (optional for backward compat)
  display_summary?: string;
  display_source?: 'evidence' | 'description' | 'name';
  evidence_excerpt?: string;
  matched_rule_name?: string;
  name_occurrence_count?: number;
  first_occurrence_unit?: number | null;
  is_first_occurrence?: boolean;
  selection_reason?: string;
}

export interface KeyEventsChapter {
  unit_index: number;
  unit_title: string;
  season_name: string;
  key_events: KeyEvent[];
}

export interface KeyEventsIndexPayload {
  version: string;
  generated_at: string;
  book_id: string;
  chapter_count: number;
  total_key_events: number;
  chapters: KeyEventsChapter[];
}

// Narrative units (generated by build_narrative_unit_boundaries.py +
// generate_narrative_units_via_gemini.py)

export interface NarrativeUnitBoundary {
  unit_id: string;
  unit_index: number;
  season_name: string;
  start_unit_index: number;
  end_unit_index: number;
  source_unit_indexes: number[];
  source_event_ids: string[];
  chapter_titles: string[];
  main_roles: string[];
  main_locations: string[];
  progress_start: number | null;
  progress_end: number | null;
  boundary_reason: string;
  input_hash: string;
}

export interface NarrativeUnitBoundariesPayload {
  version: string;
  generated_at: string;
  book_id: string;
  total_units: number;
  units: NarrativeUnitBoundary[];
}

export interface NarrativeUnit {
  unit_id: string;
  unit_index: number;
  season_name: string;
  start_unit_index: number;
  end_unit_index: number;
  source_unit_indexes?: number[];
  // Dossier fields (present after Gemini generation)
  title?: string;
  display_summary?: string;
  long_summary?: string;
  dramatic_function?: string;
  what_changes?: string;
  stakes?: string;
  // Structural fields
  main_roles: string[];
  main_locations: string[];
  source_event_ids?: string[];
  progress_start: number | null;
  progress_end: number | null;
  generated_from_input_hash?: string;
  generator?: string;
  dossier_version?: string;
  generated_at?: string;
}

export interface NarrativeUnitsPayload {
  version: string;
  generated_at: string;
  book_id: string;
  dossier_version: string;
  units: NarrativeUnit[];
}

/* ── Character Visual Profiles ── */

export interface AppearanceDetails {
  age_and_build: string;
  facial_features: string;
  hair: string;
  clothing_and_materials: string;
  color_palette: string;
  signature_items: string;
  aura_and_camera_feel: string;
}

export interface AppearanceTimelineEntry {
  phase_label: string;
  range_hint: string;
  change_summary: string;
  visual_delta: string;
  use_as_default_card: boolean;
}

export interface CharacterVisualProfile {
  role_id: string;
  canonical_name: string;
  card_title: string;
  visual_hook: string;
  initial_appearance: string;
  appearance_details: AppearanceDetails;
  negative_constraints: string[];
  image_prompt_base: string;
  image_style_notes: string;
  appearance_timeline: AppearanceTimelineEntry[];
}

export interface CharacterVisualProfilesPayload {
  version: string;
  generated_at: string;
  generator: string;
  model: string;
  roster_version: string;
  profiles: CharacterVisualProfile[];
}

/* ── High-Value Role Roster ── */

export interface HighValueRoleEntry {
  role_id: string;
  canonical_name: string;
  rank: number;
  selection_score: number;
  has_entity_profile: boolean;
  in_core_cast: boolean;
}

export interface HighValueRoleRoster {
  version: string;
  generated_at: string;
  roster_size: number;
  selection_criteria: string;
  roles: HighValueRoleEntry[];
}

/* ── Character Card Images ── */

export interface CharacterCardImageEntry {
  role_id: string;
  file_name: string;
  prompt_used: string;
  aspect_ratio: string;
  generated_at: string;
}

export interface CharacterCardImagesPayload {
  version: string;
  generated_at: string;
  model: string;
  images: CharacterCardImageEntry[];
}
