// Pipeline artifact types (JSON files under `data/`)

export interface SegmentYearIndexEntry {
  juan_index: number;
  segment_index: number;
  segment_start_time_raw: string | null;
  year: number | null;
  parse_method: string | null;
  confidence: number;
}

export interface SegmentYearIndex {
  version: string;
  cutoff_year: number;
  generated_at: string;
  segments: Record<string, SegmentYearIndexEntry>;
}

export interface SegmentYearOverrideEntry {
  year: number | null;
  reason?: string;
}

export interface SegmentYearOverrides {
  version: string;
  notes?: string;
  overrides: Record<string, SegmentYearOverrideEntry | number | null>;
}

export interface UnitProgressIndexUnit {
  unit_index: number;
  unit_title: string;
  season_index: number;
  season_name: string;
  progress_start: number;
  progress_end: number;
}

export interface UnitProgressIndexSegment {
  unit_index: number;
  segment_index: number;
  progress_index: number;
  progress_label: string;
}

export interface UnitProgressIndex {
  version: string;
  generated_at: string;
  book_id: string;
  unit_label: string;
  progress_label: string;
  total_units: number;
  total_progress_points: number;
  units: Record<string, UnitProgressIndexUnit>;
  segments: Record<string, UnitProgressIndexSegment>;
}

export interface ChapterIndexSegment {
  segment_index: number;
  progress_index: number;
  progress_label: string;
  anchor: string;
}

export interface ChapterIndexUnit {
  unit_index: number;
  juan_index: number;
  season_index: number;
  season_name: string;
  title: string;
  volume_index: number;
  volume_title: string;
  chapter_title: string;
  relative_path: string;
  progress_start: number;
  progress_end: number;
  source_document: string;
  segments: ChapterIndexSegment[];
}

export interface ChapterIndex {
  book_id: string;
  generated_at: string;
  unit_count: number;
  units: ChapterIndexUnit[];
}

export interface BookQuickFilter {
  label: string;
  unit_range: [number, number];
  progress_range: [number, number];
}

export interface BookConfig {
  book_id: string;
  title: string;
  subtitle?: string;
  unit_label: string;
  progress_label: string;
  has_geo_coordinates: boolean;
  default_tab?:
    | 'timeline'
    | 'network'
    | 'power'
    | 'locations'
    | 'map'
    | 'writerArcs'
    | 'conflicts'
    | 'foreshadowing';
  quick_filters: BookQuickFilter[];
}

export interface LocationGeocodingEntry {
  location_id: string;
  canonical_name: string;
  modern_name: string;
  query: string;
  coordinates: [number, number] | null;
  candidate_coordinates?: [number, number] | null;
  candidate_count?: number | null;
  confidence: number;
  source: string;
  evidence: string;
  info?: string;
  infocode?: string;
  needs_review: boolean;
  attempts?: number;
  updated_at: string;
}

export interface LocationGeocodingOverridesEntry {
  coordinates: [number, number];
  notes?: string;
}

export interface LocationGeocodingCache {
  version: string;
  provider: string;
  generated_at: string;
  locations: Record<string, LocationGeocodingEntry>;
  overrides: Record<string, LocationGeocodingOverridesEntry>;
}

// Chapter synopses (generated by build_chapter_synopses.py)

export interface KeyDevelopmentEvent {
  event_id: string;
  name: string;
  display_text: string;
  evidence_excerpt?: string;
  participants: string[];
  location: string;
}

export interface ChapterSynopsis {
  unit_index: number;
  unit_title: string;
  season_name: string;
  event_count: number;
  active_characters: string[];
  locations: string[];
  key_developments: string[];
  key_development_events?: KeyDevelopmentEvent[];
  synopsis: string;
  narrative_function: string;
}

export interface ChapterSynopsesPayload {
  version: string;
  generated_at: string;
  book_id: string;
  chapter_count: number;
  chapters: ChapterSynopsis[];
}

/* ── Key Events Index ── */

export interface KeyEvent {
  event_id: string;
  name: string;
  event_type: string;
  importance: 'critical' | 'major' | 'notable';
  score: number;
  location: string;
  participants: string[];
  description: string;
  significance: string;
  involved_characters: string[];
  // Card-granularity fields (optional for backward compat)
  display_summary?: string;
  evidence_excerpt?: string;
  matched_rule_name?: string;
  name_occurrence_count?: number;
  first_occurrence_unit?: number | null;
  is_first_occurrence?: boolean;
  selection_reason?: string;
}

export interface KeyEventsChapter {
  unit_index: number;
  unit_title: string;
  season_name: string;
  key_events: KeyEvent[];
}

export interface KeyEventsIndexPayload {
  version: string;
  generated_at: string;
  book_id: string;
  chapter_count: number;
  total_key_events: number;
  chapters: KeyEventsChapter[];
}
